version: '3.8'
services:
  node-app:
    container_name: node-app
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    ports:
      - "3000:3001"
    depends_on :
    - mongo-db
    volumes:
      - ./src:/app/src
      - /app/node_modules
    command: npm run dev
  # mongo-db:
  #   container_name : mongo-db
  #   image: mongo@latest
  #   restart: always
